name: DockerPublish

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - spark-3-1-3-python-3-8
          - spark-3-1-3-python-3-9
          - spark-3-2-2-python-3-8
          - spark-3-2-2-python-3-9
          - spark-3-1-3-hadoop-3-2-4-python-3-8-13-bullseye
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/spark-py:${{ matrix.tag }} -f Dockerfile.${{ matrix.tag }} .
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/spark-py:${{ matrix.tag }}
